### ISSUE TITLE
[Epic] Database stuff

### ISSUE THREAD

**Issue by Sv443** [Sv443-Network/JokeAPI#491]
A collection of all database-related stuff that is needed for the initial release.  
  
- [ ] Add table for users (#TODO)
- [ ] Add table for jokes (#TODO)
- [ ] Add table for submissions (#TODO)

**Comment by Sv443** [comment]
I think keeping them separate is a better idea since there could be edits by the original author, moderators and admins and there would be extra data associated with that. It also keeps them logically separate.

**Comment by Sv443** [comment]
Example being that submissions are being voted on by users and could have edits proposed. This has nothing to do with jokes that have been fully accepted into the joke pool already.

**Comment by cihatsarsilmaz** [comment]
> İlk sürüm için gerekli olan veritabanıyla ilgili her şeyin bir araya getirildiği bir koleksiyon.
> 
> * [x] Postgres veritabanını kurun ( [Veritabanı - Prisma için Postgres ve şablon kurulumu ](https://github.com/Sv443-Network/JokeAPI/issues/521)[ #521](https://github.com/Sv443-Network/JokeAPI/issues/521) )[](https://github.com/Sv443-Network/JokeAPI/issues/521)* [ ]  Tablo şemaları ve bağlayıcı işlevler ekleyin.
>     
>     * [x] Kullanıcılar ( [Veritabanı - Kullanıcı tablosu oluşturma ](https://github.com/Sv443-Network/JokeAPI/issues/492)[ #492](https://github.com/Sv443-Network/JokeAPI/issues/492) )[](https://github.com/Sv443-Network/JokeAPI/issues/492)* [ ] Şakalar ( [Veritabanı - Şaka tablosu oluşturma ](https://github.com/Sv443-Network/JokeAPI/issues/493)[ #493](https://github.com/Sv443-Network/JokeAPI/issues/493) )[](https://github.com/Sv443-Network/JokeAPI/issues/493)* [ ] Gönderiler ( [Veritabanı - Gönderiler tablosu oluşturma ](https://github.com/Sv443-Network/JokeAPI/issues/494)[ #494](https://github.com/Sv443-Network/JokeAPI/issues/494) )[](https://github.com/Sv443-Network/JokeAPI/issues/494)* [ ] Raporlar ( [Veritabanı - Rapor tablosu ](https://github.com/Sv443-Network/JokeAPI/issues/518)[ #518](https://github.com/Sv443-Network/JokeAPI/issues/518) oluştur )[](https://github.com/Sv443-Network/JokeAPI/issues/518)
