### ISSUE TITLE
[Epic] REST server and all its endpoints

### ISSUE THREAD

**Issue by Sv443** [Sv443-Network/JokeAPI#496]
All endpoints and other things that need to be done regarding the HTTP server.  
  
- [ ] Endpoints (and required role(s) to use them)
  - [ ] Get joke (anyone) (#495)
    - [ ] Edit / delete joke (admin) (#TODO)
  - [ ] Create / update / delete submission (user / submission author / moderator and author) (#TODO)  
    When a submission is created, the API should check for already existing similar jokes and possibly for keyboard vomit and deny the submission
    - [ ] Vote on joke submission (user) (#TODO)
    - [ ] Accept / deny joke submission (moderator) (#TODO)
    - [ ] TBD: Accept submission edit proposal & delete other proposals (moderator) (#TODO)
  - [ ] Create / update / delete user account (anyone / profile owner and admin) (#TODO)
    - [ ] Create / update / delete OAuth provider (profile owner) (#TODO)
    - [ ] Regenerate API token (profile owner and admin) (#TODO)
    - [ ] List submissions for user account (profile owner and moderator) (#TODO)
    - [ ] List jokes for user account (anyone) (#TODO)
    - [ ] Update profile settings (profile owner and admin) (#TODO)
- [ ] Rate limiting
  - [ ] General, more forgiving rate limiting for all endpoints with larger budget and shorter time frame for premium users  
    If the time frame for free users is something in the 1-24 hour range that would incentivize the paid tier(s)
  - [ ] Specialized rate limiting for endpoints that require it
- [ ] Security
  - [ ] Set good content security policy for documentation (and API itself?) (#TODO)
  - [x] Use `helmet` middleware for setting security headers
  - [x] Use `cors` middleware to allow websites to use JokeAPI
- [x] Use `compression` middleware to compress responses
