### ISSUE TITLE
[Epic] Organizational

### ISSUE THREAD

**Issue by Sv443** [Sv443-Network/JokeAPI#497]
Everything miscellaneous about organizing the API.  
  
- [ ] Create communication channels for contributors and wrapper devs
  - [ ] Mailing list and Discord channel for internal updates aimed at wrapper devs, to hear their feedback on bleeding-edge or planned features and changes and help them update their wrappers better and faster (#TODO)
  - [ ] Blog with RSS feed on the docs page with news and upcoming features that are already refined (#TODO)
- [ ] TBD: Monetization
  - [ ] Discuss tiers, features and prices
  - [ ] Discuss payment processing framework
  - [ ] Figure out how the server will know which user has which tier
  - [ ] Discuss ad placement on docs (is it even worth it?)
- [ ] Clarify process for becoming a moderator and what is required of them (#TODO)
- [ ] Clarify legality of user submitted content (they need to sign away their rights to the joke)
  - [ ] Create terms of service (#TODO)
  - [ ] Update privacy policy (#TODO)
