### ISSUE TITLE
[Epic] Deployment

### ISSUE THREAD

**Issue by Sv443** [Sv443-Network/JokeAPI#500]
- [ ] Building (#TODO)
  - [ ] Build image using Dockerfile for stage and prod
  - [ ] Publish image on GHCR
- [ ] Deploying (#TODO)
  - [ ] Use Kubernetes to deploy the built images
  - [ ] TBD: Use proxy like Traefik
